// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSiZ2t1vVj3SgnAJiquyI4L7P7Jcvj-ew',
    appId: '1:746255923146:android:7da10e1a56a080b7be8133',
    messagingSenderId: '746255923146',
    projectId: 'spiritual-insights-app',
    storageBucket: 'spiritual-insights-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCnoS9Zz2vn8QgrWYuNUqb75Dc5DbgIOE',
    appId: '1:746255923146:ios:c61e4d48cba065f9be8133',
    messagingSenderId: '746255923146',
    projectId: 'spiritual-insights-app',
    storageBucket: 'spiritual-insights-app.firebasestorage.app',
    iosBundleId: 'com.spiritualinsights.spiritualInsights',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6JQEwyg6JAEFdzBYU1PIeoIgK6qu6xd0',
    appId: '1:746255923146:web:ad4f303820449cefbe8133',
    messagingSenderId: '746255923146',
    projectId: 'spiritual-insights-app',
    authDomain: 'spiritual-insights-app.firebaseapp.com',
    storageBucket: 'spiritual-insights-app.firebasestorage.app',
    measurementId: 'G-N073M9398D',
  );

}